name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [23]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Display Haxe version
        run: haxe -version

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Check Node.js version
        run: node -v

      - name: Install Node.js dependencies
        run: npm install

      - name: Build
        run: make js

      - name: Run tests
        run: make
